---
title: "Iteration and listcols"
author: "Susie Dong"
date: "2023-10-26"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```

## R Markdown

### LOFR words

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring") 

lotr_load_and_tidy = function(path = "data/LotR_Words.xslx", cell_change, movie_name) {
  
  movie_df =
    readxl::read_excel(path, range = cell) |>
    mutate(movie = movie_name) |>
    janitor::clean_names() |>
    pivot_longer(
      female:male,
      names_to = "sex",
      values_to = "words"
    ) |>
    select(movie, everything())
  
  movie_df
}

lot
```

# Oct 31

## list

```{r}
1 = 
  list(
    vec_numeric = 1:5,
    vec_char = LETTERS,
    matrix = matrix(1:10, nrow = 5, ncol = 2)
    summary = summary(rnorm(100))
  )

```

## loops

```{r}
list_norm_samples =
  list(
    a = rnorm()
  )
```

mean and sd function

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```

```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```


```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
}
```

## use `map`

```{r}
Map(list_norm_samples, mean_and_sd)

output = map(list_norm_samples, summary)
```


## create DF

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d")
    samp = list_norm_samples
  )
```

```{r}
mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[1]])

map(listcol_df$samp, mean_and_sd)

listcol_df |>
  mutate(
    mean_sd = map(samp, mean_and_sd),
    median = map(samp, median)) |>
  select(name, mean_sd) |>
  unnest(mean_sd)

```

## NSDUH

```{r}
usduh_import(nsduh_html, 1, "marj")
usduh_import(nsduh_html, 4, "cocaine")
usduh_import(nsduh_html, 5, "heroin")
```

import data using a for loop.

```{r}
table_input = list(1,4,5)
name_input = list("marj", "cocaine", "heroin")

output = vector("list", length = 3)

for (i in c(1:3)) {
  
  output[[1]] = nsduh_import(nsduh_html, table_input[[1]], name_input[[1]])
  
}

nsduh_df = bind_rows(output)
```


Try again, using maps!!!

```{r}


nsduh_df =
  tibble(
    name = c("marj", "cocaine", "heroin"),
    number = c(1,4,5)
  ) |>
  mutate(
    table = map(number, nsduh_import, html = nsduh_html)) |>
  unnest(table)

map(nsduh_df$number, nsduh_import, html = nsduh_html)
```



```{r}
weather_nest_df =
weather_df |>
  nest(df = date:tmin)
```

can i regress "tmax" on "tmin" for each of these...?

```{r}
central_park_df =
  weather_nest_df |>
  pull(df) |>
  nth(1)
```

fit a linear regression for ccentrol park

```{r}
weather_lm = function(df) {
  lm(tmax = tmin, data = centrol_park_df)
}

weather = 
```

let's try for a loop

```{r}
input_list = weather_nest_df |> pull(df)
output = vecter("list", length = 3)

for(i in 1:3) {
  output[[1]] = weather_lm(input_list[[1]])
}
  
weather_nest_df |>
  mutate(models = map(df, weather_lm))
```








